import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./css/style.css";
import Nav from "./components/UI/Nav";

import dynamic from "next/dynamic";

const Particles = dynamic(() => import("./components/UI/Particles"), {
  ssr: true, // This ensures the component is only rendered on the client side
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth ">
      <body
        className={`${inter} font-inter antialiased bg-black text-slate-100 tracking-tight`}
      >
        <div className="flex flex-col min-h-screen   overflow-hidden supports-[overflow:clip]:overflow-clip">
          <Particles className="absolute inset-0 -z-10 fade-in" />
          <div
            className="absolute inset-0 -z-10  rounded-b-[3rem] pointer-events-none overflow-hidden"
            aria-hidden="true"
          >
            <div className="absolute left-1/2 -translate-x-1/2 bottom-0 -z-10">
              <div className="purple-glow fade-in "></div>
            </div>
          </div>
          {children}
          <Nav />
        </div>
      </body>
    </html>
  );
}
